let installed = false
const css = `
.ddl-panel{height:100%;box-sizing:border-box;overflow:auto;padding:16px;color:var(--text-primary,#222);background:var(--bg-body,#fff);font:13px/1.45 var(--font-sans,system-ui,sans-serif)}
.ddl-header{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;border-bottom:1px solid var(--border-color,rgba(0,0,0,.12));padding-bottom:12px}.ddl-header h2{font-size:16px;margin:0}.ddl-header p{margin:3px 0 0;color:var(--text-secondary,#666)}
.ddl-toolbar,.ddl-actions{display:flex;gap:8px;flex-wrap:wrap}.ddl-toolbar{padding:12px 0}.ddl-btn,.ddl-icon-btn{border:1px solid var(--border-color,rgba(0,0,0,.18));border-radius:7px;background:var(--bg-elevated,#fff);color:inherit;padding:6px 9px;cursor:pointer}.ddl-primary{background:var(--brand-color,#5e5ce6);border-color:var(--brand-color,#5e5ce6);color:#fff}.ddl-icon-btn{font-size:18px;padding:1px 8px}
.ddl-form{display:flex;flex-direction:column;gap:9px;border:1px solid var(--border-color,rgba(0,0,0,.12));background:var(--bg-elevated,#fafafa);border-radius:8px;padding:12px;margin:0 0 12px}.ddl-form label{display:flex;flex-direction:column;gap:4px;color:var(--text-secondary,#666)}.ddl-form input,.ddl-run-select,.ddl-stage-head select{box-sizing:border-box;border:1px solid var(--border-color,rgba(0,0,0,.2));border-radius:6px;padding:6px;background:var(--input-bg,#fff);color:inherit}.ddl-actions{justify-content:flex-end}.ddl-run-select{width:100%;margin-bottom:10px}
.ddl-empty{border:1px dashed var(--border-color,rgba(0,0,0,.2));border-radius:8px;padding:24px 14px;text-align:center;color:var(--text-secondary,#666)}.ddl-summary{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:10px 12px;border-radius:8px;background:var(--bg-elevated,#f7f7fa);margin-bottom:10px}.ddl-summary span{font-weight:650}.ddl-summary strong{font-size:12px;padding:2px 6px;border-radius:99px;background:#e7e5ff;color:#4238b8}.ddl-summary small{margin-left:auto;color:var(--text-secondary,#666)}
.ddl-stages{list-style:none;margin:0;padding:0}.ddl-stages>li{border-left:2px solid var(--border-color,rgba(0,0,0,.16));padding:0 0 13px 13px;margin-left:8px;position:relative}.ddl-stage-head{display:flex;align-items:center;gap:7px}.ddl-stage-head strong{flex:1}.ddl-stage-head select{max-width:112px;font-size:12px;padding:4px}.ddl-dot{width:10px;height:10px;background:#a1a1aa;border-radius:50%;position:absolute;left:-6px}.ddl-stages [data-status=passed]>.ddl-stage-head>.ddl-dot{background:#16a34a}.ddl-stages [data-status=failed]>.ddl-stage-head>.ddl-dot{background:#dc2626}.ddl-stages [data-status=blocked]>.ddl-stage-head>.ddl-dot{background:#d97706}.ddl-stages [data-status=running]>.ddl-stage-head>.ddl-dot{background:#2563eb}.ddl-stages p{margin:5px 0;color:var(--text-secondary,#666)}.ddl-evidence{margin:5px 0;padding-left:18px}.ddl-evidence small{color:var(--text-secondary,#666)}.ddl-evidence a{color:var(--brand-color,#5e5ce6)}.ddl-link{background:none;border:0;padding:2px 0;color:var(--brand-color,#5e5ce6);cursor:pointer}.ddl-error{background:#fef2f2;color:#b91c1c;padding:8px;border-radius:6px}
`
export function injectStyles(): void { if (installed) return; installed = true; const el = document.createElement('style'); el.textContent = css; document.head.append(el) }
